"""add unique medicine per prescription

Revision ID: 12c67bd06e9e
Revises: b9d7fc768edd
Create Date: 2026-09-08 17:57:26.622566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12c67bd06e9e'
down_revision: Union[str, Sequence[str], None] = 'b9d7fc768edd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_prescription_medicine', 'prescription_detail', ['prescription_id', 'medicine_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_prescription_medicine', 'prescription_detail', type_='unique')
    # ### end Alembic commands ###
