"""update user model

Revision ID: 1fd837d83d7f
Revises: 9d1169be8f8d
Create Date: 2026-09-02 17:14:13.849813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1fd837d83d7f'
down_revision: Union[str, Sequence[str], None] = '9d1169be8f8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient', 'gender')
    op.add_column('user', sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='user_gender'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'gender')
    op.add_column('patient', sa.Column('gender', mysql.ENUM('MALE', 'FEMALE'), nullable=True))
    # ### end Alembic commands ###
