"""create initial clinic schema

Revision ID: 9d1169be8f8d
Revises: 
Create Date: 2026-08-31 01:32:24.585947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d1169be8f8d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicine',
    sa.Column('medicine_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('stock_qty', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DISCONTINUED', name='medicine_status'), server_default='Active', nullable=False),
    sa.PrimaryKeyConstraint('medicine_id')
    )
    op.create_table('specialty',
    sa.Column('specialty_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('specialty_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'RECEPTIONIST', 'DOCTOR', 'PATIENT', name='user_role'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'LOCKED', name='user_status'), server_default='Active', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('admin',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('doctor',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('qualification', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('specialty_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['specialty_id'], ['specialty.specialty_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('patient',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='patient_gender'), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('receptionist',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('chat_session',
    sa.Column('session_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_chat_session_patient_id'), 'chat_session', ['patient_id'], unique=False)
    op.create_table('working_schedule',
    sa.Column('schedule_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'OFF', name='working_schedule_status'), server_default='Active', nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('schedule_id'),
    sa.UniqueConstraint('doctor_id', 'work_date', 'start_time', 'end_time', name='uq_doctor_working_schedule')
    )
    op.create_index(op.f('ix_working_schedule_doctor_id'), 'working_schedule', ['doctor_id'], unique=False)
    op.create_table('appointment',
    sa.Column('appointment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('chat_session_id', sa.Integer(), nullable=True),
    sa.Column('appointment_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'COMPLETED', 'CANCELLED', name='appointment_status'), server_default='Pending', nullable=False),
    sa.Column('created_by', sa.Enum('PATIENT', 'RECEPTIONIST', 'AI', name='appointment_create_by'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['chat_session_id'], ['chat_session.session_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.user_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['schedule_id'], ['working_schedule.schedule_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('appointment_id')
    )
    op.create_index(op.f('ix_appointment_chat_session_id'), 'appointment', ['chat_session_id'], unique=True)
    op.create_index(op.f('ix_appointment_patient_id'), 'appointment', ['patient_id'], unique=False)
    op.create_index(op.f('ix_appointment_schedule_id'), 'appointment', ['schedule_id'], unique=False)
    op.create_table('chat_message',
    sa.Column('message_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('sender_type', sa.Enum('PATIENT', 'AI', name='chat_sender_type'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('intent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_session.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index(op.f('ix_chat_message_session_id'), 'chat_message', ['session_id'], unique=False)
    op.create_table('invoice',
    sa.Column('invoice_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('UNPAID', 'PAID', 'CANCELLED', name='invoice_status'), server_default='Unpaid', nullable=False),
    sa.Column('payment_method', sa.Enum('CASH', 'ONLINE', name='payment_method'), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.appointment_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('invoice_id'),
    sa.UniqueConstraint('appointment_id')
    )
    op.create_table('medical_record',
    sa.Column('record_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('symptoms', sa.Text(), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('examined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.appointment_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('record_id'),
    sa.UniqueConstraint('appointment_id')
    )
    op.create_table('prescription',
    sa.Column('prescription_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['medical_record.record_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('prescription_id'),
    sa.UniqueConstraint('record_id')
    )
    op.create_table('prescription_detail',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prescription_id', sa.Integer(), nullable=False),
    sa.Column('medicine_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('dosage', sa.String(length=255), nullable=False),
    sa.Column('usage_note', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicine.medicine_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescription.prescription_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescription_detail_medicine_id'), 'prescription_detail', ['medicine_id'], unique=False)
    op.create_index(op.f('ix_prescription_detail_prescription_id'), 'prescription_detail', ['prescription_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prescription_detail_prescription_id'), table_name='prescription_detail')
    op.drop_index(op.f('ix_prescription_detail_medicine_id'), table_name='prescription_detail')
    op.drop_table('prescription_detail')
    op.drop_table('prescription')
    op.drop_table('medical_record')
    op.drop_table('invoice')
    op.drop_index(op.f('ix_chat_message_session_id'), table_name='chat_message')
    op.drop_table('chat_message')
    op.drop_index(op.f('ix_appointment_schedule_id'), table_name='appointment')
    op.drop_index(op.f('ix_appointment_patient_id'), table_name='appointment')
    op.drop_index(op.f('ix_appointment_chat_session_id'), table_name='appointment')
    op.drop_table('appointment')
    op.drop_index(op.f('ix_working_schedule_doctor_id'), table_name='working_schedule')
    op.drop_table('working_schedule')
    op.drop_index(op.f('ix_chat_session_patient_id'), table_name='chat_session')
    op.drop_table('chat_session')
    op.drop_table('receptionist')
    op.drop_table('patient')
    op.drop_table('doctor')
    op.drop_table('admin')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_table('specialty')
    op.drop_table('medicine')
    # ### end Alembic commands ###
